directories:
  - .git
  - log
  - public/system
  - tmp
  - vendor
  - build
  - dist
files:
  - .DS_Store
  - database.yml
  - favicon.ico
  - requirements.txt
patterns:
  - '*.pdf'
  - '*.tmp'
  - '*.md'
  # - '*.py'
